### ISSUE TITLE
Can't install node modules

### ISSUE THREAD

**Issue by jasonburnell98** [sophtron/tbdex-widget#1]
I tried to run this project locally, but I can't install node modules and am receiving the following error: 
I am using node version 16.4.1

```
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm ERR! code E401
npm ERR! Unable to authenticate, your authentication token seems to be invalid.
npm ERR! To correct this please trying logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/developer/.npm/_logs/2022-09-16T03_19_31_060Z-debug-0.log
```

**Comment by sophtron** [comment]
Thanks @jasonburnell98 for your quick interest , this repo does need a big clean up. we are still working on that 

in order to finish `npm install`, please delete the `package-log.json` and `yarn.lock`, then use command `npm install  --legacy-peer-deps`, this is caused by the `nextjs` template we used, 

We'll push changes to fix this issue and update the document as well. thanks you again!
